use_frameworks!

platform :ios, '8.0'

target 'RZColorfulSwift_Example' do
  pod 'RZColorfulSwift', :path => '../'
  pod 'SnapKit'
  target 'RZColorfulSwift_Tests' do
    inherit! :search_paths

    # pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
